# Generated by Django 4.2.4 on 2023-09-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, null=True)),
                ('item_desc', models.TextField(null=True)),
                ('item_img', models.ImageField(null=True, upload_to='item_image/')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
