# Generated by Django 4.2.5 on 2023-09-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitems',
            name='item_img',
            field=models.ImageField(null=True, upload_to='api/item_image/'),
        ),
    ]
